application: garageapp
version: beta-2
runtime: java
public_root: /public
sessions_enabled: true

resource_files:
  - exclude: /build/**

handlers: 
  - url: /*
    servlet: controllers.SiteController
    name: site
    
  - url: /m/*
    servlet: controllers.MobileController
    name: mobile
              
  - url: /user/*
    servlet: controllers.UserController
    name: user    
    
  - url: /migrate/*
    servlet: controllers.MigrationController
    name: migrate
    
  - url: /task/*
    servlet: controllers.TaskController
    name: task
    login: admin