application: motocashapp
version: alfa-1
runtime: java
public_root: /public
sessions_enabled: true

resource_files:
  - exclude: /build/**

handlers: 
  - url: /*
    servlet: controllers.SiteController
    name: site
    
  - url: /m/*
    servlet: controllers.MobileController
    name: mobile
              
  - url: /admin/*
    servlet: controllers.AdminController
    name: admin    
    
  - url: /user/*
    servlet: controllers.UserController
    name: user    