#application: kyblslev
application: motocashapp
version: alfa1
runtime: java
public_root: /public
sessions_enabled: true

resource_files:
  - exclude: /build/**

handlers: 
    
  - url: /admin/*
    servlet: controllers.AdminController
    name: admin    
    
  - url: /customer/*
    servlet: controllers.CustomerController
    name: customer

  - url: /0e411e1bbaba90b26c1cf25142cf4457/*
    servlet: controllers.UploadController
    name: upload
    
  - url: /*
    servlet: controllers.SiteController
    name: site        